### ISSUE TITLE
Run without Doctrine

### ISSUE THREAD

**Issue by pavkriz** [r-bruha/nette-generator#4]
Generator is not able to run without the following configuration:
```
extensions:
     doctrine: Kdyby\Doctrine\DI\OrmExtension

doctrine:
    user: root
    password: password
    dbname: database
    metadata:
        App: %appDir%
```

Saying:
```
ERROR: application encountered an error and can not continue.
```
without any clue (though tracy/ladenka reports doctrine-related error in the web app)

Consider fix in order to run generator without this configuration when using `Nette\Database` or report proper error in CLI.
